services:
  - type: web
    name: emergency-lighting-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn backend.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: REDIS_URL
        fromService:
          type: redis
          name: emergency-lighting-redis
          property: connectionString
      - key: GOOGLE_API_KEY
        sync: false  # Set manually in Render dashboard
      - key: UPLOAD_DIR
        value: /tmp/uploads
      - key: OUTPUT_DIR  
        value: /tmp/output
    
  - type: worker
    name: emergency-lighting-worker
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: celery -A backend.worker worker --loglevel=info --concurrency=1
    envVars:
      - key: REDIS_URL
        fromService:
          type: redis
          name: emergency-lighting-redis
          property: connectionString
      - key: GOOGLE_API_KEY
        sync: false
  - type: redis
    name: emergency-lighting-redis
    plan: starter
